### ISSUE TITLE
puppet-lint warning about quoted boolean values

### ISSUE THREAD

**Issue by kasimon** [smoeding/puppet-debconf#1]
puppet-lint forbids strings to be exactly a boolean value in resource definitions, so
```
debconf { 'dash/sh':
  type  => 'boolean',
  value => 'true',
}
```
will cause a puppet-lint error, which in a restrictive environment may prevent the code from being checked into a production codebase. Using a verbatim boolean value does not work too, as your module expects a string. Currently we have to use the following (ugly) workaround:
```
debconf { 'dash/sh':
  type  => 'boolean',
  value => 'true ',  # space after "true" to work around puppet-lint warning
}
```
A possible workaround would be to add special handling for boolean values and require them to be provided as nativ puppet boolean values. Unfortunately I'm not a ruby coder, so I can't easily provide a pull request.

**Comment by kasimon** [comment]
The puppet-lint warning added for completeness: http://puppet-lint.com/checks/quoted_booleans/

**Comment by smoeding** [comment]
Yes, this is a known issue with puppet-lint. I'm not sure if there is an easy for Puppet 3. In Puppet 4 the parameter could be declared as a `Variant[String,Boolean]` that would restrict the data type accordingly. But I'm a bit reluctant in breaking backwards compatibility right now.

The best solution for now would be to disable the puppet-lint check for the specific line using a [control comment](http://puppet-lint.com/controlcomments/):

```
debconf { 'dash/sh':
  type  => 'boolean',
  value => 'true',      # lint:ignore:quoted_booleans
}
```

At least this does not require any _magic_ change to the value itself.
 
I should probably include this in the module documentation.

**Comment by kasimon** [comment]
Honestly I didn't know that possibility. Works good enough for me. Thank you for the very helpful module!

**Comment by smoeding** [comment]
OK, nice. I would like to keep this issue open as a reminder to add that detail to the module docs.
