### ISSUE TITLE
Resource type debconf not found

### ISSUE THREAD

**Issue by stefanost67** [smoeding/puppet-debconf#11]
Hello,
I installed your module on puppet 8 in order to use it with the saz/timezone module.

I get this on a Debian 12 agent:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'debconf' (file: /etc/puppetlabs/code/environments/production/modules/timezone/manifests/init.pp, line: 75, column: 7) on node debian12tpl.my.com
`

Whereas on the server I get this:

`root@puppet8:/# puppet resource debconf
`
`Error: Could not run: To support listing resources of this type the 'debian' provider needs to implement an 'instances' class method returning the current set of resources. We recommend porting your module to the simpler Resource API instead: https://puppet.com/search/docs?keys=resource+api
`

Any idea on how to solve this issue?

Thanks, Stefano.

**Comment by smoeding** [comment]
To address your second point: this is really not implemented here. The `resource` command tries to locate all instances of a given type and the type needs to provide an implementation to do that. I did not implement this here. I don't really recall the exact reasons but one point probably was, that I didn't want to call the debconf executable a couple of times to retrieve this data. The standard file type also does not privide this information as it would have to read all files in the system to do that. (But I must admit that the file type privides a better message to explain the issue.)

Your first issue: that looks strange. Can you verify that the debconf module is visible in `/etc/puppetlabs/code/environments/production/modules`? Have you used the `puppet generate types` command in the past and did not run it now?

**Comment by stefanost67** [comment]
Hello,
I ran the `puppet generate types` command, of which I did not know, and everything is fine now.
I do not understand if the necessity of running this command is expected or I found myself in a peculiar situation.

Thanks!!!

**Comment by smoeding** [comment]
Hi Stefano,

keep in mind that you probably will need to run `puppet generate types` again when you update/install a module using a custom type/provider. It seems to be connected to the internal caching that the puppetserver uses.

I also pushed a new release to the forge to provide a better message when `puppet resource debconf` is used. 

Regards,
Stefan
