### ISSUE TITLE
debconf trigged on every puppet run

### ISSUE THREAD

**Issue by cyberox** [smoeding/puppet-debconf#2]
When I use debconf to preseed my mysql root password, this debconf is triggered on every puppet run:

```
Debug: Debconf: calling exists? for mysql-server/root_password
Debug: Debconf: caching data for mysql-server/root_password
Debug: Debconf: getting items for package mariadb-server-10.1
Debug: Executing: '/usr/bin/debconf-show mariadb-server-10.1'
Debug: Debconf: item mysql-server/root_password_again => (password omitted)
Debug: Debconf: item mysql-server/root_password => (password omitted)
Debug: Debconf: item mysql-server/password_mismatch => 
Debug: Debconf: item mysql-server/error_setting_password => 
Debug: Debconf: get mysql-server/root_password
Debug: Debconf: set mysql-server/root_password to secret
Debug: Debconf: updating mysql-server/root_password
Notice: /Stage[main]/Mysql::Package/Debconf[mysql-server/root_password]/value: value changed '(password omitted)' to 'secret'
Debug: /Stage[main]/Mysql::Package/Debconf[mysql-server/root_password]: The container Class[Mysql::Package] will propagate my refresh event

```
This is caused by the fact that the password is stored as "(password omitted)".
Maybe it is a better solution to check "password" types in the password database:

```
echo "get mysql-server/root_password" | debconf-communicate mariadb-server-10.1
0 secret
```

**Comment by smoeding** [comment]
Yes, this is obviously a bug in the current implementation. The current implementation uses `debconf-show` and it seems to be unable to retrieve the value of a password typed item. Using `debconf-communicate` looks like the proper interface to these values.

**Comment by smoeding** [comment]
I just commit an updated provider that fixes the issue for me. If you want to verify this in your environment you can download the updated file: [`debian.rb`](https://raw.githubusercontent.com/smoeding/puppet-debconf/master/lib/puppet/provider/debconf/debian.rb). Replace the file of the same name in the debconf module at `.../modules/debconf/lib/puppet/provider/debconf/debian.rb` in your Puppet environment.

**Comment by cyberox** [comment]
Yes, it is working now. Thank you for the quick resolution!
