### ISSUE TITLE
debconf resouce type missing

### ISSUE THREAD

**Issue by jurgenweber** [smoeding/puppet-debconf#3]
```Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'debconf' at /etc/puppetlabs/puppet/modules/timezone/manifests/init.pp:84:7```

maybe need to add git@github.com:smoeding/puppet-debconf.git as a dependency in the readme?

**Comment by smoeding** [comment]
The error is triggered by the `timezone` module, which is probably this module: https://github.com/saz/puppet-timezone

The `metadata.json` file contains the correct dependency, so if you used the standard Puppet commands to install the module from the forge, then the dependency should be installed with it.

The README does not contain a description of the dependency, that's right. If you install the timezone module from source then all you could do is also look into `metadata.json`.

Unfortunately there is nothing I can do about this as the `timezone` module is not maintained by me. You will have to contact @saz about this problem.

**Comment by smoeding** [comment]
Closing this issue as it can't be fixed in this repository.
